mnemo = ["cruise flip live fatigue give staff target odor absent curtain absurd silly", "cover identify solve motor measure elephant shift lab recycle angle pulp wise", "final sheriff already hurt summer favorite hurry bread frozen guide garden ahead"]

